# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Quassarian Viper
email: viper.incarnation@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A Homo Sapiens made by pile of quarks. Passionate Learner.
twitter_username: QuassarianViper
github_username: q-viper
search: true
repository: "q-viper/q-viper.github.io"
issues_repo: "q-viper/q-viper.github.io"
# Build settings
markdown: kramdown
kramdown:
   input: GFM
   math_engine: mathjax
   highlighter: rouge
syntax_highlighter_opts:
    block:
        line_numbers: true
google-site-verification: "-NAJsggtItjDHz0RXX60dTYYgfPzcfBp-oUg34Gf2wQ"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-159044949-2"
    anonymize_ip: true # default

logo: "/assets/images/pp.jpg"
teaser: "/assets/images/project.jpg"
remote_theme: mmistakes/minimal-mistakes
# theme: minimal-mistakes-jekyll
# Outputting
# permalink: /:categories/:title/
permalink: /:year/:month/:day/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
# timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
minimal_mistakes_skin: "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Quassarian Viper"
  avatar : "/assets/images/pp.jpg"
  bio    : "Pile of Quarks as Homo Sapiens."
  links:
    # - label: "Website"
    #   icon: "fas fa-fw fa-link"
    #   url: "https://acharyaramkrishna.com.np"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/QuassarianViper"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/q-viper"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/qramkrishna/"

footer:
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://acharyaramkrishna.com.np"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/QuassarianViper"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/q-viper"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/ramkrishna-acharya-91a217183/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      classes: wide
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
comments:
  provider: "utterances"
  utterances:
    theme:  "github-dark" #"github-light"
    issue_term:
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/